module.exports = {
    urlSample : 'url format sample: http://localhost:4000?date=2018-04-10&location=berlin&time=12:01 (time, date and location parameters optional)',
    day: {
        sunday: 0,
        sun: 0,
        monday: 1,
        mon: 1,
        tuesday: 2,
        tue: 2,
        wednesday: 3,
        wed: 3,
        thursday: 4,
        thu: 4,
        friday: 5,
        fri: 5,
        saturday: 6,
        sat: 6,
        tomorrow: 1,
    },
    month: {
        jan: 01,
        january: 01,
        feb: 02,
        february: 02,
        mar: 03,
        march: 03,
        apr: 04,
        april: 04,
        may: 05,
        jun: 06,
        june: 06,
        jul: 07,
        july: 07,
        aug: 08,
        august: 08,
        sep: 09,
        september: 09,
        oct: 10,
        october: 10,
        nov: 11,
        november: 11,
        dec: 12,
        december: 12
    }
}

